server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 997304393
    url: jdbc:mariadb://localhost:3306/datapool
  jpa:
    open-in-view: false