server:
  port: 8080
  servlet:
    context-path: /location

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/datapool
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
  jpa:
    # 视图层不打开实体对象
    open-in-view: false
    # 显示运行sql语句
    show-sql: true
    # 自动生成表结构
    generate-ddl: true