server:
  port: 8080
  servlet:
    context-path: /location

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234567890
    url: jdbc:mariadb://localhost:3306/datapool
  jpa:
    open-in-view: false